# Generated by Django 4.2.1 on 2023-05-23 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Summary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("E", "Дошкільна"),
                            ("D", "Повна загальна середня"),
                            ("C", "Професійна"),
                            ("B", "Фахова передвища"),
                            ("A", "Вища"),
                        ],
                        max_length=1,
                    ),
                ),
                ("profession", models.CharField(max_length=64)),
                ("end_of_education", models.DateField()),
                ("skills", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=64)),
                ("views", models.IntegerField()),
                ("user_id", models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="candidates",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
