# Generated by Django 4.2.1 on 2023-05-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_summary_alter_vacancy_candidates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
